version: '3'
services:
  # stack:
  #     container_name: stack
  #     image: localstack/localstack
  #     ports:
  #       - "4566:4566"
  #       - "4572:4572"
  #       - "4570:4570"
  #       - "4581:4581"
  #       - "4571:4571"
  #       - "4578:4578"
  #       - "4575:4575"
  #       - "4576:4576"
  #       - "4574:4574"
  #       - "4568:4568"
  #       - "8080:8080"
  sqs:
      container_name: sqs
      image: softwaremill/elasticmq-native
      ports:
        - "9324:9324"
        - "9325:9325"
      # volumes:
      #   - elasticmq.conf /etc/elasticmq/elasticmq.conf
  sls:
      container_name: sls
      build: .
      volumes:
        - .:/app
      ports:
        - "3000:3000"
        - "3001:3001"
        - "3002:3002"
        - "3003:3003"
      depends_on:
        - sqs
        # - stack
      environment:
        - SLS_DEBUG=*
        - NODE_ENV=test
      command: bash -c "tail -f /dev/null"